name: ${project.name}
main: net.plazmix.avocato.PlazmixAvocatoPlugin
version: ${project.version}
description: ${project.description}
website: ${project.url}

author: Frotter

depend: [PlazmixAPI, CloudNet-Bridge]
